CC=clang++
CXX=clang++
CXXFLAGS=-Wall -Wextra -Werror -std=c++17 -O3
LDLIBS=-lpthread

EXECUTABLES=writing-threads time-loop histogram find-decimals

all: $(EXECUTABLES)

clean:
	@rm -f *.o
	@rm -f $(EXECUTABLES)
